label: Edison Agency

# Admin
admin: [ 0.0.0.0, 3001 ]
admin-insecure-mode: true

# Load toolbox plugin
plugin:
  - redis_queue.v1_0.events
plugin-config: ./configs/agency-redis.yml

# Default endpoint, should be overriden by command or env
endpoint: http://localhost:3001

# Transport (Plugin)
inbound-transport:
  - [ redis_queue.v1_0.inbound, redis, 0 ]
outbound-transport: redis_queue.v1_0.outbound

# Ledger
no-ledger: true

# Multi-tenancy
# multitenant: true
# jwt-secret: insecure-jwt-secret
# multitenant-admin: true

# Connections
debug-connections: true
debug-credentials: true
debug-presentations: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true

# Credentials and Presentations
# preserve-exchange-records: true
# auto-store-credential: true
# auto-respond-credential-proposal: true
# auto-respond-credential-offer: true
# auto-respond-credential-request: true
#
# auto-respond-presentation-proposal: true
# auto-respond-presentation-request: true
# auto-verify-presentation: true

# Wallet
# wallet-name: default
# wallet-type: indy
# wallet-key: "insecure, for use in demo only"
# auto-provision: true
