label: Edison Mediator

# Admin
admin: [0.0.0.0, 3002]
admin-insecure-mode: true

# Load toolbox plugin
plugin:
  - redis_queue.v1_0.events
# plugin-config: ./configs/agency-redis-mediator.yml
plugin-config-value:
  - redis_queue.connection.connection_url=redis://default:test1234@172.28.0.103:6379
  - redis_queue.outbound.acapy_outbound_topic=acapy_inbound
  - redis_queue.outbound.mediator_mode=true

# Default endpoint, should be overridden by command or env
endpoint: http://localhost:3002

# Transport (Plugin)
inbound-transport:
  - [http, 0.0.0.0, 3000]
outbound-transport: redis_queue.v1_0.outbound

# Ledger
no-ledger: true

# Connections
debug-connections: true
debug-credentials: true
debug-presentations: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true

# Mediation
open-mediation: true
# Credentials and Presentations
# preserve-exchange-records: true
# auto-store-credential: true
# auto-respond-credential-proposal: true
# auto-respond-credential-offer: true
# auto-respond-credential-request: true
#
# auto-respond-presentation-proposal: true
# auto-respond-presentation-request: true
# auto-verify-presentation: true

# Wallet
# wallet-name: default
# wallet-type: indy
# wallet-key: "insecure, for use in demo only"
# auto-provision: true
